default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['WT_DB_USERNAME'] %>
  password: <%= ENV['WT_DB_PASSWORD'] %>
  host: <%= ENV['WT_DB_HOSTNAME'] %>

development:
  <<: *default
  database: whosthere_development

test:
  <<: *default
  database: whosthere_test

production:
  <<: *default
  database: <%= ENV['WT_DB_DATABASE'] %>
  username: <%= ENV['WT_DB_USERNAME'] %>
  password: <%= ENV['WT_DB_PASSWORD'] %>
  host:     <%= ENV['WT_DB_HOSTNAME'] %>
